### ISSUE TITLE
Demo source

### ISSUE THREAD

**Issue by hackery** [wuxx/nanoCH32V203#5]
Could you add the source for those demo apps to the repo please?

**Comment by wuxx** [comment]
hello, the demo source is under software directory.
https://github.com/wuxx/CH32V203-makefile-example/tree/637b7ba6edf3252ab927d729ddd5ae98053bb13c

**Comment by hackery** [comment]
No, the code in there doesn't match any of the three bin files in the `demo` directory. There are two versions of `blink`, and an lcd demo which behaves differently to the one from the makefile-example repo.

**Comment by wuxx** [comment]
blink source code
https://github.com/wuxx/nanoCH32V203/tree/master/doc/EVT/EXAM/GPIO/GPIO_Toggle

lcd demo
https://github.com/wuxx/CH32V203-makefile-example/tree/637b7ba6edf3252ab927d729ddd5ae98053bb13c
